- platform: wunderground
  api_key: !secret wu_api_key
  monitored_conditions:
    - alerts
    - temp_f
    - feelslike_f
    - wind_gust_mph
    - precip_today_in
    - precip_1d_in
    - temp_high_1d_f
    - temp_low_1d_f
    - wind_gust_1d_mph
    - weather
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n

# - platform: arlo #2018/03/17 Temperary Disable
#   monitored_conditions:
#     - captured_today
#     - last_capture
#     - total_cameras
#     - battery_level
#     - signal_strength

- platform: opensprinkler
  monitored_conditions:
    - opensprinkler_station
    - opensprinkler_schedule
    - opensprinkler_lastrun
    - opensprinkler_rain

- platform: mqtt
  name: "Garage Temperature"
  state_topic: "tele/sonoff/SENSOR"
  value_template: "{{ value_json['BME280'].Temperature }}"
  unit_of_measurement: "°F"

- platform: mqtt
  name: "Garage Humidity"
  state_topic: "tele/sonoff/SENSOR"
  value_template: "{{ value_json['BME280'].Humidity }}"
  unit_of_measurement: "%"

- platform: mqtt
  name: "Garage Pressure"
  state_topic: "tele/sonoff/SENSOR"
  value_template: "{{ value_json['BME280'].Pressure | round(2) }}"
  unit_of_measurement: "hPa"

- platform: template
  sensors:
    tp_link_amps:
      value_template: '{{ states.switch.garage_vacuum.attributes["Current"] | replace(" A", "") | float }}'
      unit_of_measurement: 'A'
    tp_link_watts:
      value_template: '{{ states.switch.garage_vacuum.attributes["Current consumption"] | replace(" W", "") | float }}'
      unit_of_measurement: 'W'
    tp_link_kw:
      value_template: '{{ states.switch.garage_vacuum.attributes["Total consumption"] | replace(" kW", "") | float }}'
      unit_of_measurement: 'kW'
    tp_link_volts:
      value_template: '{{ states.switch.garage_vacuum.attributes["Voltage"] | replace(" V", "") | float }}'
      unit_of_measurement: 'V'

#Time and Date Sensor
- platform: time_date
  display_options:
    - 'date_time'

- platform: uptime

#- platform: command_line
#  name: SSL certificate expiry
#  unit_of_measurement: days
#  scan_interval: 86400
#  command: "ssl-cert-check -b -c /etc/letsencrypt/live/hassnuc.duckdns.org/cert.pem | awk '{ print $NF }'"